apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -o ./kubernetes/
    kompose.version: 1.33.0 (3ce457399)
  labels:
    io.kompose.service: catalog-app
  name: catalog-app
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: catalog-app
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -o ./kubernetes/
        kompose.version: 1.33.0 (3ce457399)
      labels:
        io.kompose.network/centralrepository3-app-network: "true"
        io.kompose.service: catalog-app
    spec:
      containers:
        - env:
            - name: AllowedHosts
              value: '*'
            - name: MongoDbSettings__ConnectionString
              value: mongodb://mymongodb:27017
            - name: MongoDbSettings__DatabaseName
              value: DLS
            - name: RabbitMQSettings__HostName
              value: rabbitmq
            - name: RabbitMQSettings__Password
              value: password
            - name: RabbitMQSettings__UserName
              value: user
          image: simonlindegaardm/centralrepository3-catalog-app
          name: catalog-app
          ports:
            - containerPort: 80
              hostPort: 8070
              protocol: TCP
            - containerPort: 7026
              hostPort: 8443
              protocol: TCP
      restartPolicy: Always
