apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -o ./kubernetes/
    kompose.version: 1.33.0 (3ce457399)
  labels:
    io.kompose.service: email-app
  name: email-app
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: email-app
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -o ./kubernetes/
        kompose.version: 1.33.0 (3ce457399)
      labels:
        io.kompose.network/centralrepository3-app-network: "true"
        io.kompose.service: email-app
    spec:
      containers:
        - image: simonlindegaardm/centralrepository3-email-app
          name: email-app
          ports:
            - containerPort: 80
              hostPort: 8040
              protocol: TCP
      restartPolicy: Always
