apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -o ./kubernetes/
    kompose.version: 1.33.0 (3ce457399)
  labels:
    io.kompose.service: mymongodb
  name: mymongodb
spec:
  ports:
    - name: "27017"
      port: 27017
      targetPort: 27017
  selector:
    io.kompose.service: mymongodb
