apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -o ./kubernetes/
    kompose.version: 1.33.0 (3ce457399)
  labels:
    io.kompose.service: order-app
  name: order-app
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: order-app
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -o ./kubernetes/
        kompose.version: 1.33.0 (3ce457399)
      labels:
        io.kompose.network/centralrepository3-app-network: "true"
        io.kompose.service: order-app
    spec:
      containers:
        - env:
            - name: AllowedHosts
              value: '*'
            - name: ConnectionStrings__DefaultConnection
              value: Server=order-db;Database=OrderServiceDB;User=sa;Password=Qwerty123!;TrustServerCertificate=True;
            - name: RabbitMQ__HostName
              value: rabbitmq
            - name: RabbitMQ__Password
              value: password
            - name: RabbitMQ__UserName
              value: user
          image: simonlindegaardm/centralrepository3-order-app
          name: order-app
          ports:
            - containerPort: 80
              hostPort: 8080
              protocol: TCP
      restartPolicy: Always
