apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -o ./kubernetes/
    kompose.version: 1.33.0 (3ce457399)
  labels:
    io.kompose.service: order-app
  name: order-app
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: order-app
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -o ./kubernetes/
        kompose.version: 1.33.0 (3ce457399)
      labels:
        io.kompose.network/centralrepository3-app-network: "true"
        io.kompose.service: order-app
    spec:
      containers:
        - env:
            - name: ConnectionStrings__DefaultConnection
              value: Server=centralrepository3-order-db-1;Database=OrderServiceDB;User=sa;Password=Qwerty123!;TrustServerCertificate=True;
          image: order-app
          name: order-app
          ports:
            - containerPort: 80
              hostPort: 8080
              protocol: TCP
      restartPolicy: Always
