apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -o ./kubernetes/
    kompose.version: 1.33.0 (3ce457399)
  labels:
    io.kompose.service: payment-app
  name: payment-app
spec:
  ports:
    - name: "8050"
      port: 8050
      targetPort: 80
  selector:
    io.kompose.service: payment-app
