apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -o ./kubernetes/
    kompose.version: 1.33.0 (3ce457399)
  labels:
    io.kompose.service: user-app
  name: user-app
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: user-app
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -o ./kubernetes/
        kompose.version: 1.33.0 (3ce457399)
      labels:
        io.kompose.network/centralrepository3-app-network: "true"
        io.kompose.service: user-app
    spec:
      containers:
        - env:
            - name: ConnectionStrings__DefaultConnection
              value: Server=my_mysql_db;Database=UserServiceDB;Uid=root;Pwd=1234;Port=3306;
          image: user-app
          name: user-app
          ports:
            - containerPort: 80
              hostPort: 8060
              protocol: TCP
      restartPolicy: Always
